# AWS Self-Hosted Kubernetes Cluster
#
# Setup:
#   astroctl cloud aws selfHosted setup --account-id <id> --region <region> --cluster-name <name>
# Verify:
#   astroctl cloud aws selfHosted connect --cluster-name <name>
#
# Usage: astroctl infra k8s apply -f aws.yaml
# Docs:  https://astropulse.io/docs/latest/platform/cluster-pipeline/provisioner/self-hosted/aws

apiVersion: platform.astropulse.io/v1
kind: K8sCluster
spec:
  clusterName: v-aws-cluster
  provider: aws
  region: us-west-2 # aws configure get region
  provisioner:
    type: selfHosted
    selfHosted:
      accountId: "<YOUR_AWS_ACCOUNT_ID>"
      bucketName: "<from-setup-output>"

      # networkId: vpc-018f2dec8bb5ddfdd  # optional: bring your own VPC

      credentials:
        type: vault

  clusterSpec:
    controlPlane:
      nodeGroup:
        name: control-plane
        machineTypes:
          - t3.medium
    dataPlane:
      nodeGroups:
        - name: worker-ng
          minNode: 3
          maxNode: 6
          instanceType: ondemand
          machineTypes:
            - t3.large
          labels:
            environment: production
