apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: astro-cert
  namespace: cert-manager
spec:
  secretName: nginx-global-default-tls-cert
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.example.com"
  dnsNames:
    - "*.example.com"
    - "*.dev.example.com"
    - "*.prod.example.com"
