apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
spec:
  replicas: 3
  image:
    application: confluentinc/cp-server:7.6.0
    init: confluentinc/confluent-init-container:2.8.0
  dataVolumeCapacity: 100Gi
  metricReporter:
    enabled: false
  podTemplate:
    tolerations:
      - key: "node.cluster.platform.astropulse.io/purchase-option"
        operator: "Equal"
        value: "ondemand"
        effect: "NoSchedule"
      - key: "node.cluster.platform.astropulse.io/type"
        operator: "Equal"
        value: "dataplane"
        effect: "NoSchedule"
  dependencies:
    zookeeper:
      endpoint: zookeeper.confluent.svc.cluster.local:2181