apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
spec:
  replicas: 3
  image:
    application: confluentinc/cp-zookeeper:7.6.0
    init: confluentinc/confluent-init-container:2.8.0
  podTemplate:
    tolerations:
      - key: "node.cluster.platform.astropulse.io/purchase-option"
        operator: "Equal"
        value: "ondemand"
        effect: "NoSchedule"
      - key: "node.cluster.platform.astropulse.io/type"
        operator: "Equal"
        value: "dataplane"
        effect: "NoSchedule"
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 10Gi 