name: grafana-service
profileName:  profile3
namespace: monitoring
source:
  type: helm
  helm: 
    repo: 
      repoURL: https://grafana.github.io/helm-charts
      chartVersion: 8.0.0
      chartName: grafana
    # https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
    values:
     type: object
     object:
       namespaced: false
       persistence:
         type: pvc
         enabled: true
         size: 10Gi
       adminUser: admin
       adminPassword: 66YQ8CYImcatKjM3JDx5ykBYb9EQeQSZcKIhY6llq4
       plugins:
        - vertamedia-clickhouse-datasource
        - grafana-clickhouse-datasource
       