name: grafana-service
profileName: pre-selected-aws-cluster
source:
  type: helm
  helm: 
    repo: 
      repoURL: https://grafana.github.io/helm-charts
      chartVersion: 8.0.0
      chartName: grafana
    values:
     type: object
     object:
       namespaced: false
       persistence:
         type: pvc
         enabled: true
         size: 10Gi
       adminUser: admin
       adminPassword: 66YQ8CYImcatKjM3JDx5ykBYb9EQeQSZcKIhY6llq4
       tolerations:
        - key: "node.cluster.platform.astropulse.io/purchase-option"
          operator: "Equal"
          value: "ondemand"
          effect: "NoSchedule" 
        - key: "node.cluster.platform.astropulse.io/type"
          operator: "Equal"
          value: "dataplane"
          effect: "NoSchedule"
